name: check-spelling

on: [push, pull_request]

jobs:
  check-spelling:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: codespell-project/actions-codespell@master
        with:
          skip: ./.git,./layouts,./themes,./static,./bin,./test/sharness/t0280-plugin-dag-jose-data,./docs/AUTHORS,*.mod,*.sum,*.pdf,*.data
          ignore_words_file: ./.github/workflows/spell_ignore.txt
# uncomment this to make warning only - not failing the checks
#          only_warn: 1
